name: Build Linux

on: [push]


jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: |
        sudo apt install    \
        libfreetype6-dev    \
        libx11-dev          \
        libxrandr-dev       \
        libgl1-mesa-dev     \
        libudev-dev         \
        libopenal-dev       \
        libflac-dev         \
        libogg-dev          \
        libvorbis-dev -y

    - name: Build
      run:  |
        cd tools/nuget
        ls -al
        ./build.linux.sh macos-x64
