name: Build

on: [push]


jobs:
  Linux:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: |
        sudo apt install    \
        libfreetype6-dev    \
        libx11-dev          \
        libxrandr-dev       \
        libgl1-mesa-dev     \
        libudev-dev         \
        libopenal-dev       \
        libflac-dev         \
        libogg-dev          \
        libvorbis-dev -y

    - name: Build
      run:  |
        cd tools/nuget
        ./build.linux.sh linux-x64
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: linux-x64
        # Directory containing files to upload
        path: tools/nuget/CSFML/runtimes
  
  Windows:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run:  |
          cd tools/nuget
          cmake.exe --version
       # .\build.win.ps1
      #- name: Upload artifact x64
       # uses: actions/upload-artifact@v1.0.0
        #with:
          # Artifact name
         # name: win-x64
          # Directory containing files to upload
          #path: tools/nuget/CSFML/runtimes
        
  Mac:
    runs-on: [macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Tools
      run: |
        brew install coreutils
    - name: Build
      env:
        CC: clang
        CXX: clang++
      run:  |
        cd tools/nuget
        ls -al
      #./build.linux.sh macos-x64

  Package:
    needs: [Linux,Windows,Mac]
    runs-on: [ubuntu-latest]
    steps:
      - name: Create Directory
        run: mkdir -p tools/nuget/CSFML/runtimes
      # Dowload Linux Artifact
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: linux-x64
          # Destination path
          path: tools/nuget/CSFML/runtimes
          # artifact source
          #source: # optional, default is current
      # Dowload Windows Artifact
      # Dowload macOS Artifact
      - name: Package Nuget
        run: |
          cd tools/nuget
          ls -al CSFML/runtimes
        #./pushnuget.sh <secret key>
