name: Build

on: [push]


jobs:
  build:

    runs-on: [macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Tools
      run: |
        brew install coreutils
        brew install --with-toolchain llvm
    - name: Build
      run:  |
        cd tools/nuget
        ls -al
        ./build.linux.sh macos-x64
