name: Build

on: [push]


jobs:
  build:

    runs-on: [macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Create build directory
      run: mkdir build
    - name: Cmake
      run:  |
        cd tools/nuget
        ./build.linux.sh macos-x64
