name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create build directory
      run: mkdir build
    - name: Cmake
      run:  |
        cd build
        cmake ..
