name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create build directory
      run: |
        mkdir build,
        cd build
        ls ..
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
