name: Build Linux

on: [push]


jobs:
  buildLinux:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: |
        sudo apt install    \
        libfreetype6-dev    \
        libx11-dev          \
        libxrandr-dev       \
        libgl1-mesa-dev     \
        libudev-dev         \
        libopenal-dev       \
        libflac-dev         \
        libogg-dev          \
        libvorbis-dev -y

    - name: Build
      run:  |
        cd tools/nuget
        ./build.linux.sh linux-x64
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: linux-x64
        # Directory containing files to upload
        path: tools/nuget/CSFML/runtimes/linux-x64/native
  
  BuildWindows:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run:  |
          cd tools/nuget
          .\build.win.ps1 win-x64
      - name: Upload artifact x64
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: win-x64
          # Directory containing files to upload
          path: tools/nuget/CSFML/runtimes/win-x64/native
      - name: Upload artifact x86
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: win-x86
          # Directory containing files to upload
          path: tools/nuget/CSFML/runtimes/win-x86/native
