name: Build Linux

on: [push]


jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: |
        sudo apt install xorg
    - name: Build
      run:  |
        cd tools/nuget
        ls -al
        ./build.linux.sh macos-x64
